class XMLConstants:
    TREE_SUMMARY = "summary"
    TREE_METHODS = "methods"
    TREE_METHOD = "method"
    TREE_FLOWS = "flows"
    TREE_FLOW = "flow"
    TREE_SINK = "to"
    TREE_SOURCE = "from"
    TREE_GAPS = "gaps"
    TREE_GAP = "gap"
    TREE_CLEARS = "clears"
    TREE_CLEAR = "clear"
    TREE_HIERARCHY = "hierarchy"
    TREE_INTERFACE = "interface"

    ATTRIBUTE_FORMAT_VERSION = "fileFormatVersion"
    ATTRIBUTE_IS_INTERFACE = "isInterface"
    ATTRIBUTE_ID = "num"
    ATTRIBUTE_METHOD_SIG = "id"
    ATTRIBUTE_IS_EXCLUDED = "isExcluded"
    ATTRIBUTE_FLOWTYPE = "sourceSinkType"
    ATTRIBUTE_PARAMTER_INDEX = "ParameterIndex"
    ATTRIBUTE_ACCESSPATH = "AccessPath"
    ATTRIBUTE_ACCESSPATHTYPES = "AccessPathTypes"
    ATTRIBUTE_BASETYPE = "BaseType"
    ATTRIBUTE_ERROR = "ERROR"
    ATTRIBUTE_TAINT_SUB_FIELDS = "taintSubFields"
    ATTRIBUTE_GAP = "gap"
    ATTRIBUTE_IS_ALIAS = "isAlias"
    ATTRIBUTE_TYPE_CHECKING = "typeChecking"
    ATTRIBUTE_IGNORE_TYPES = "ignoreTypes"
    ATTRIBUTE_CUT_SUBFIELDS = "cutSubfields"
    ATTRIBUTE_MATCH_STRICT = "matchStrict"
    ATTRIBUTE_NAME = "name"
    ATTRIBUTE_SUPERCLASS = "superClass"

    VALUE_TRUE = "true"
    VALUE_FALSE = "false"

    VALUE_PARAMETER = "parameter"
    VALUE_FIELD = "field"
    VALUE_RETURN = "return"
